const express = require("express");
const router = express.Router();

const activityRoute = require("./activity");
const activityTaskRoute = require("./activityTask");
const calendarRoute = require("./calendar");
const authRoute = require("./auth");
const scheduleRoute = require("./schedule");
const schedulesRoute = require("./schedules");
const userRoute = require("./user");
const personnelRoute = require("./personnel");
const youthRoute = require("./youth");
const nguonRoute = require("./nguon");
const qndbRoute = require("./qndb");
const department = require("./department");
const kpiRoute = require("./kpi");

router.use('/activities', activityRoute);
router.use('/activities-task', activityTaskRoute);
router.use('/calendar', calendarRoute);
router.use('/auth', authRoute);
router.use('/schedule', scheduleRoute);
router.use('/schedules', schedulesRoute);
router.use('/users', userRoute);
router.use('/personnel', personnelRoute);
router.use('/youth', youthRoute);
router.use('/nguon', nguonRoute);
router.use('/qndb', qndbRoute);
router.use('/department', department);
router.use('/kpi', kpiRoute);
module.exports = router;
